name: The Collective
favicon: null
layout_spectrum: 0.89769
typography_spectrum: 0.93221
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: THE CLLTVE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F6F6F8'
    - '#231738'
    - '#C4471E'
    - '#EA883E'
    - '#8E8D93'
  brandStrength: 1
  lightness: 0.7653061
  saturation: 0.4044038
  rhythmicContrast: 0.7803437
purpose: []
